# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opencosmo_remote/messages/column.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opencosmo_remote/messages/column.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&opencosmo_remote/messages/column.proto\"\xdb\x01\n\rDerivedColumn\x12\x14\n\nlhs_scalar\x18\n \x01(\x01H\x00\x12%\n\x0blhs_derived\x18\x0b \x01(\x0b\x32\x0e.DerivedColumnH\x00\x12\x14\n\nlhs_column\x18\x0c \x01(\tH\x00\x12\x14\n\nrhs_scalar\x18\x14 \x01(\x01H\x01\x12%\n\x0brhs_derived\x18\x15 \x01(\x0b\x32\x0e.DerivedColumnH\x01\x12\x14\n\nrhs_column\x18\x16 \x01(\tH\x01\x12\x16\n\x02op\x18\x03 \x01(\x0e\x32\n.operationB\x05\n\x03lhsB\x05\n\x03rhs\"\x8f\x01\n\x16WithNewColumnStatement\x12\x35\n\x07\x63olumns\x18\x01 \x03(\x0b\x32$.WithNewColumnStatement.ColumnsEntry\x1a>\n\x0c\x43olumnsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.DerivedColumn:\x02\x38\x01*e\n\toperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\x12\x07\n\x03POW\x10\x04\x12\t\n\x05\x45XP10\x10\x05\x12\t\n\x05LOG10\x10\x06\x12\x08\n\x04SQRT\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opencosmo_remote.messages.column_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WITHNEWCOLUMNSTATEMENT_COLUMNSENTRY']._loaded_options = None
  _globals['_WITHNEWCOLUMNSTATEMENT_COLUMNSENTRY']._serialized_options = b'8\001'
  _globals['_OPERATION']._serialized_start=410
  _globals['_OPERATION']._serialized_end=511
  _globals['_DERIVEDCOLUMN']._serialized_start=43
  _globals['_DERIVEDCOLUMN']._serialized_end=262
  _globals['_WITHNEWCOLUMNSTATEMENT']._serialized_start=265
  _globals['_WITHNEWCOLUMNSTATEMENT']._serialized_end=408
  _globals['_WITHNEWCOLUMNSTATEMENT_COLUMNSENTRY']._serialized_start=346
  _globals['_WITHNEWCOLUMNSTATEMENT_COLUMNSENTRY']._serialized_end=408
# @@protoc_insertion_point(module_scope)
