# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opencosmo_remote/messages/filter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opencosmo_remote/messages/filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&opencosmo_remote/messages/filter.proto\x12\x19opencosmo_remote.messages\"i\n\x0c\x43olumnFilter\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\t\x12:\n\x0b\x66ilter_type\x18\x02 \x01(\x0e\x32%.opencosmo_remote.messages.FilterType\x12\r\n\x05value\x18\x03 \x01(\x02\"K\n\x0f\x46ilterStatement\x12\x38\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\'.opencosmo_remote.messages.ColumnFilter*.\n\nFilterType\x12\x06\n\x02GT\x10\x00\x12\x07\n\x03GTE\x10\x01\x12\x06\n\x02LT\x10\x02\x12\x07\n\x03LTE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opencosmo_remote.messages.filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTERTYPE']._serialized_start=253
  _globals['_FILTERTYPE']._serialized_end=299
  _globals['_COLUMNFILTER']._serialized_start=69
  _globals['_COLUMNFILTER']._serialized_end=174
  _globals['_FILTERSTATEMENT']._serialized_start=176
  _globals['_FILTERSTATEMENT']._serialized_end=251
# @@protoc_insertion_point(module_scope)
