# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opencosmo_remote/messages/open.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opencosmo_remote/messages/open.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$opencosmo_remote/messages/open.proto\"@\n\rOpenStatement\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x19\n\x06\x64types\x18\x02 \x03(\x0e\x32\t.DataType\"V\n\x15InternalOpenStatement\x12\x14\n\x0c\x64\x61taset_path\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x19\n\x06\x64types\x18\x03 \x03(\x0e\x32\t.DataType*\x88\x01\n\x08\x44\x61taType\x12\x13\n\x0fHALO_PROPERTIES\x10\x00\x12\x12\n\x0eHALO_PARTICLES\x10\x01\x12\x11\n\rHALO_PROFILES\x10\x02\x12\x15\n\x11GALAXY_PROPERTIES\x10\x03\x12\x14\n\x10GALAXY_PARTICLES\x10\x04\x12\x13\n\x0fGALAXY_PROFILES\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opencosmo_remote.messages.open_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=195
  _globals['_DATATYPE']._serialized_end=331
  _globals['_OPENSTATEMENT']._serialized_start=40
  _globals['_OPENSTATEMENT']._serialized_end=104
  _globals['_INTERNALOPENSTATEMENT']._serialized_start=106
  _globals['_INTERNALOPENSTATEMENT']._serialized_end=192
# @@protoc_insertion_point(module_scope)
