# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opencosmo_remote/messages/query.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'opencosmo_remote/messages/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opencosmo_remote.messages import select_pb2 as opencosmo__remote_dot_messages_dot_select__pb2
from opencosmo_remote.messages import filter_pb2 as opencosmo__remote_dot_messages_dot_filter__pb2
from opencosmo_remote.messages import take_pb2 as opencosmo__remote_dot_messages_dot_take__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%opencosmo_remote/messages/query.proto\x12\x19opencosmo_remote.messages\x1a&opencosmo_remote/messages/select.proto\x1a&opencosmo_remote/messages/filter.proto\x1a$opencosmo_remote/messages/take.proto\"\xa0\x02\n\x13OpenCosmoQueryStage\x12\x43\n\x06select\x18\n \x01(\x0b\x32\x31.opencosmo_remote.messages.DatasetSelectStatementH\x00\x12<\n\x06\x66ilter\x18\x0b \x01(\x0b\x32*.opencosmo_remote.messages.FilterStatementH\x00\x12\x38\n\x04take\x18\x0c \x01(\x0b\x32(.opencosmo_remote.messages.TakeStatementH\x00\x12\x43\n\ntake_range\x18\r \x01(\x0b\x32-.opencosmo_remote.messages.TakeRangeStatementH\x00\x42\x07\n\x05query')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opencosmo_remote.messages.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENCOSMOQUERYSTAGE']._serialized_start=187
  _globals['_OPENCOSMOQUERYSTAGE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
