# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from opencosmo_remote.messages import open_pb2 as opencosmo__remote_dot_messages_dot_open__pb2
from opencosmo_remote.messages import query_pb2 as opencosmo__remote_dot_messages_dot_query__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in opencosmo_remote/messages/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenCosmoQueryHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoQueryStage = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/DoQueryStage',
                request_serializer=opencosmo__remote_dot_messages_dot_query__pb2.OpenCosmoQueryStage.SerializeToString,
                response_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/Execute',
                request_serializer=opencosmo__remote_dot_messages_dot_query__pb2.Token.SerializeToString,
                response_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.FromString,
                _registered_method=True)
        self.OpenRemote = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/OpenRemote',
                request_serializer=opencosmo__remote_dot_messages_dot_open__pb2.OpenStatement.SerializeToString,
                response_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.WriteData = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/WriteData',
                request_serializer=opencosmo__remote_dot_messages_dot_query__pb2.WriteStatement.SerializeToString,
                response_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.FromString,
                _registered_method=True)
        self.CloseRemote = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/CloseRemote',
                request_serializer=opencosmo__remote_dot_messages_dot_query__pb2.Token.SerializeToString,
                response_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.Exit = channel.unary_unary(
                '/opencosmo_remote.messages.OpenCosmoQueryHandler/Exit',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class OpenCosmoQueryHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoQueryStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenRemote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseRemote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenCosmoQueryHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoQueryStage': grpc.unary_unary_rpc_method_handler(
                    servicer.DoQueryStage,
                    request_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.OpenCosmoQueryStage.FromString,
                    response_serializer=opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.Token.FromString,
                    response_serializer=opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.SerializeToString,
            ),
            'OpenRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenRemote,
                    request_deserializer=opencosmo__remote_dot_messages_dot_open__pb2.OpenStatement.FromString,
                    response_serializer=opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.SerializeToString,
            ),
            'WriteData': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteData,
                    request_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.WriteStatement.FromString,
                    response_serializer=opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.SerializeToString,
            ),
            'CloseRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseRemote,
                    request_deserializer=opencosmo__remote_dot_messages_dot_query__pb2.Token.FromString,
                    response_serializer=opencosmo__remote_dot_messages_dot_query__pb2.CloseResponse.SerializeToString,
            ),
            'Exit': grpc.unary_unary_rpc_method_handler(
                    servicer.Exit,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opencosmo_remote.messages.OpenCosmoQueryHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opencosmo_remote.messages.OpenCosmoQueryHandler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenCosmoQueryHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoQueryStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/DoQueryStage',
            opencosmo__remote_dot_messages_dot_query__pb2.OpenCosmoQueryStage.SerializeToString,
            opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/Execute',
            opencosmo__remote_dot_messages_dot_query__pb2.Token.SerializeToString,
            opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/OpenRemote',
            opencosmo__remote_dot_messages_dot_open__pb2.OpenStatement.SerializeToString,
            opencosmo__remote_dot_messages_dot_query__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/WriteData',
            opencosmo__remote_dot_messages_dot_query__pb2.WriteStatement.SerializeToString,
            opencosmo__remote_dot_messages_dot_query__pb2.OutputPath.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/CloseRemote',
            opencosmo__remote_dot_messages_dot_query__pb2.Token.SerializeToString,
            opencosmo__remote_dot_messages_dot_query__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opencosmo_remote.messages.OpenCosmoQueryHandler/Exit',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
