# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opencosmo_remote/messages/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opencosmo_remote/messages/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opencosmo_remote.messages import select_pb2 as opencosmo__remote_dot_messages_dot_select__pb2
from opencosmo_remote.messages import filter_pb2 as opencosmo__remote_dot_messages_dot_filter__pb2
from opencosmo_remote.messages import take_pb2 as opencosmo__remote_dot_messages_dot_take__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%opencosmo_remote/messages/query.proto\x12\x19opencosmo_remote.messages\x1a&opencosmo_remote/messages/select.proto\x1a&opencosmo_remote/messages/filter.proto\x1a$opencosmo_remote/messages/take.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x02\n\x13OpenCosmoQueryStage\x12/\n\x05token\x18\x01 \x01(\x0b\x32 .opencosmo_remote.messages.Token\x12\x43\n\x06select\x18\n \x01(\x0b\x32\x31.opencosmo_remote.messages.DatasetSelectStatementH\x00\x12<\n\x06\x66ilter\x18\x0b \x01(\x0b\x32*.opencosmo_remote.messages.FilterStatementH\x00\x12\x38\n\x04take\x18\x0c \x01(\x0b\x32(.opencosmo_remote.messages.TakeStatementH\x00\x12\x43\n\ntake_range\x18\r \x01(\x0b\x32-.opencosmo_remote.messages.TakeRangeStatementH\x00\x42\x07\n\x05query\"!\n\rQueryResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1a\n\nOutputPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05Token\x12\x0c\n\x04uuid\x18\x01 \x01(\t2\xa3\x02\n\x15OpenCosmoQueryHandler\x12n\n\x0c\x44oQueryStage\x12..opencosmo_remote.messages.OpenCosmoQueryStage\x1a(.opencosmo_remote.messages.QueryResponse\"\x00(\x01\x30\x01\x12R\n\x07\x45xecute\x12 .opencosmo_remote.messages.Token\x1a%.opencosmo_remote.messages.OutputPath\x12\x46\n\nOpenRemote\x12\x16.google.protobuf.Empty\x1a .opencosmo_remote.messages.Tokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opencosmo_remote.messages.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENCOSMOQUERYSTAGE']._serialized_start=216
  _globals['_OPENCOSMOQUERYSTAGE']._serialized_end=553
  _globals['_QUERYRESPONSE']._serialized_start=555
  _globals['_QUERYRESPONSE']._serialized_end=588
  _globals['_OUTPUTPATH']._serialized_start=590
  _globals['_OUTPUTPATH']._serialized_end=616
  _globals['_TOKEN']._serialized_start=618
  _globals['_TOKEN']._serialized_end=639
  _globals['_OPENCOSMOQUERYHANDLER']._serialized_start=642
  _globals['_OPENCOSMOQUERYHANDLER']._serialized_end=933
# @@protoc_insertion_point(module_scope)
