syntax = "proto3";
package opencosmo_remote.messages;

import "opencosmo_remote/messages/select.proto";
import "opencosmo_remote/messages/filter.proto";
import "opencosmo_remote/messages/take.proto";
import "opencosmo_remote/messages/open.proto";
import "opencosmo_remote/messages/column.proto";
import "google/protobuf/empty.proto";


message OpenCosmoQueryStage {
  Token token = 1;
  oneof query {
    DatasetSelectStatement select = 10;
    FilterStatement filter = 11;
    TakeStatement take = 12;
    TakeRangeStatement take_range = 13;
    WithNewColumnStatement new_columns = 14;
    
  }
}

message DatasetSpecification {
  uint64 length = 1;
  repeated string columns = 2;
  bool is_lightcone = 3;
}

message StructureCollectionSpecification {
  uint64 length = 1;
  repeated string datasets = 2;
}


message OpenCosmoDataSpecification {
  oneof spec {
    DatasetSpecification ds = 10;
    StructureCollectionSpecification sc = 11;
  }
}

message QueryResponse {
  OpenCosmoDataSpecification spec = 1;
  string message = 2;
  optional Token new_token = 3;
}
message OutputPath {
  string path = 1;
}
message Token {
  string uuid = 1;
}

message OpenResponse {
  Token token = 1;
  string repr = 2;
}

message CloseResponse {
  string res = 1;
}


service OpenCosmoQueryHandler {
  rpc DoQueryStage(OpenCosmoQueryStage) returns (QueryResponse) {};
  rpc Execute(Token) returns (OutputPath);
  rpc OpenRemote(OpenStatement) returns (QueryResponse);
  rpc CloseRemote(Token) returns (CloseResponse);
  rpc Exit(google.protobuf.Empty) returns (google.protobuf.Empty);
}
